### ISSUE TITLE
Cargo-license returns N\A for every dependency.

### ISSUE THREAD

**Issue by maciejkula** [onur/cargo-license#10]
Both compiled from source (newest master) and installed via cargo `cargo install cargo-license`, the binary results in `"N\A"` licenses for _every_ dependency (even when the actual crates have valid licenses on crates.io).

**Comment by maciejkula** [comment]
Update: this is due to the following `.gitconfig` setting:
```
[url "git@github.com:"]
     insteadOf = https://github.com/
```

This is common for Go users (because of the limitations of the Go toolchain). Removing this setting fixes the issue.

**Comment by dalance** [comment]
I think this issue is resolved by changing from `cargo` to `cargo-metadata` @ https://github.com/onur/cargo-license/pull/14.
I close this issue. If it is not resolved, please reopen.
