### ISSUE TITLE
Separate licenses by normal/build/development dependencies

### ISSUE THREAD

**Issue by l0calh05t** [onur/cargo-license#18]
It would be great if cargo-license could separate between normal, build and development dependencies, because in most cases the latter two do not affect licensing of the resulting library. Current `cargo_metadata` should have the necessary information: https://docs.rs/cargo_metadata/0.8.0/cargo_metadata/enum.DependencyKind.html

**Comment by U007D** [comment]
Came here to leave this same suggestion.
