### ISSUE TITLE
`cargo license` reads command line arguments wrong and fails to execute

### ISSUE THREAD

**Issue by Lokathor** [onur/cargo-license#23]
```
D:\dev\beryllium>cargo license
error: Found argument 'license' which wasn't expected, or isn't valid in this context

USAGE:
    cargo-license.exe [FLAGS] [OPTIONS]

For more information try --help
```
It looks like the command line arguments are off by 1 or something?

**Comment by birkenfeld** [comment]
Also found this right now. Running the bare binary (i.e. `$ cargo-license`) works...

**Comment by Stargateur** [comment]
Look like cargo will not alter args, tarpaulin way https://github.com/xd009642/tarpaulin/blob/73ffc5ac96238e93882726fc16a50d832cfe7af2/src/main.rs#L106.
