### ISSUE TITLE
Parses AND/OR license incorrectly

### ISSUE THREAD

**Issue by Timmmm** [onur/cargo-license#24]
`crossbeam-channel` has the license [`MIT/Apache-2.0 AND BSD-2-Clause`](https://github.com/crossbeam-rs/crossbeam/blob/master/crossbeam-channel/Cargo.toml), which they intend to mean `((MIT OR APACHE) AND BSD)`, but cargo-license outputs `Apache-2.0 AND BSD-2-Clause OR MIT`.

The issue is that it just [assumes normal operator precedence](https://github.com/onur/cargo-license/blob/master/src/lib.rs#L11), but a reasonable person would not interpret `A/B AND C` as `A/(B AND C)`.

Not a trivial problem to solve (are you going to add support for brackets? I don't think so). I would suggest you only normalise if `/`/`OR` and `AND` are not mixed (see what I did there?).

**Comment by dalance** [comment]
Now `/` is deprecated.
https://github.com/rust-lang/cargo/pull/4898

So I think this case should be written like `A AND C OR B AND C`.
https://github.com/crossbeam-rs/crossbeam/commit/81eea4788949ed848d4788d08231e75c8ac54e1e
