### ISSUE TITLE
After `cargo install cargo-license`, `cargo-license` works, but `cargo license` does not

### ISSUE THREAD

**Issue by U007D** [onur/cargo-license#25]
```bash
▶ cargo license
error: Found argument 'license' which wasn't expected, or isn't valid in this context

USAGE:
    cargo-license [FLAGS] [OPTIONS]

For more information try --help
```
Many other `cargo install xxx` commands work as expected.
Bash/Pop!_OS(Ubuntu) 19.10,
cargo 1.42.0 (86334295e 2020-01-31)

Any ideas?

**Comment by rotty** [comment]
I experience the same behavior on Debian buster (amd64), with the same cargo version. For humans, it is merely an inconvenience, but it also breaks CI scripts that rely on the previous (and "standard") behavior.

**Comment by patrickelectric** [comment]
Same problem here
