### ISSUE TITLE
Boost-1.0 vs BSL-1.0

### ISSUE THREAD

**Issue by epsilon-0** [onur/cargo-license#28]
There seems to be a slight misunderstanding in the `Boost-1.0` reporting as there is a `BSL-1.0` (bussiness source license): https://mariadb.com/bsl-faq-adopting/

Fix: Report `Boost-1.0` and not as `BSL-1.0`

**Comment by dalance** [comment]
BSL-1.0 is the official SPDX identifier of Boost Software License 1.0.
And BUSL-1.1 is Business Software License 1.1.

https://spdx.org/licenses/

I think the notation should follow SPDX because Cargo requires SPDX identifier for the licence field.
