### ISSUE TITLE
cargo-license crashes when running it

### ISSUE THREAD

**Issue by staktrace** [onur/cargo-license#3]
I tried running `cargo license` in the `sample` folder of the `servo/webrender` repository to try and see the license of all the dependencies. However I got a crash instead:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io, (Some(Error { repr: Os { code: 2, message: "No such file or directory" } }), stack backtrace:
   0:     0x55a22e62f06d - backtrace::backtrace::trace::h16372ee7bf1517e5
   1:     0x55a22e62f6f2 - backtrace::capture::Backtrace::new::hcc43c50c4b11c693
   2:     0x55a22e57533f - <cargo_license::Error as core::convert::From<std::io::error::Error>>::from::hdf8702df7c2b799c
   3:     0x55a22e5742a9 - cargo_license::get_dependencies_from_cargo_lock::h8e93364dce42dbf0
   4:     0x55a22e56e40d - cargo_license::main::he7497a14b2ac292f
   5:     0x55a22e6e9cca - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
   6:     0x55a22e6e152a - std::panicking::try<(),fn()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                         - std::panic::catch_unwind<fn(),()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                         - std::rt::lang_start
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
   7:     0x7fc7cfb7b82f - __libc_start_main
   8:     0x55a22e56dbd8 - _start
   9:                0x0 - <unknown>))', ../src/libcore/result.rs:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by onur** [comment]
cargo-license is only working if there is a `Cargo.lock` file in current working directory and also cargo-license using an old version of cargo, and doesn't support workspaces yet. I'll try to update cargo.

**Comment by onur** [comment]
Ignore my previous message.

cargo-license is only working when there is a `Cargo.lock` in current working directory. But since `sample` folder is using a `workspace` definition, cargo-license failing to find a Cargo.lock.

Currently, there is no difference running cargo-license in `webrender` and `webrender/sample`. And all members of a workspace is using same `Cargo.lock`.

I think cargo-license needs a real toml parser for workspaces. It is fair to say, cargo-license doesn't support workspaces ATM.

**Comment by dalance** [comment]
In my understanding, cargo-license takes the information through cargo-metadata now, and can handle workspace correctly.
I close this issue. If this issue is not resolved, please reopen.
