### ISSUE TITLE
Please, update to newer cargo, dependencies no longer build

### ISSUE THREAD

**Issue by jan-hudec** [onur/cargo-license#5]
The `cargo` version used depends on `libgit2-sys` v0.4.6, which no longer builds on Debian Testing. Since newer versions build just fine, the easiest fix would be to update to newer cargo.

The errors are:
```
libgit2-sys-0.4.6/libgit2/src/openssl_stream.c:146:3: error: dereferencing pointer to incomplete type ‘BIO {aka struct bio_st}’
libgit2-sys-0.4.6/libgit2/src/openssl_stream.c:204:1: error: variable ‘git_stream_bio_method’ has initializer but incomplete type
```

**Comment by onur** [comment]
Thanks for reporting. I am using Debian Sid and it is building fine.

But I'll definitely update this crate.

**Comment by jan-hudec** [comment]
Works ok.
