### ISSUE TITLE
Call for maintenance and new releases

### ISSUE THREAD

**Issue by PsiACE** [onur/cargo-license#57]
hi @onur @dalance 

This crate does not appear to be in a state of active maintenance, nor are there any plans for a new release.

We have chosen to fork this crate in order to get a stable build. But for now, I'd like us to go 'upstream first', preferably using a crate that is published to crates.io. see https://github.com/datafuselabs/databend/issues/6969

I am not sure if you would like to release a new release, or if a new maintainer is needed, we would be happy to help.

**Comment by dalance** [comment]
Thank you for your notice.
I'll review open PRs and release in this week.

**Comment by dalance** [comment]
I published v0.5.0.

**Comment by PsiACE** [comment]
thank you!
