### ISSUE TITLE
Virtual workspace

### ISSUE THREAD

**Issue by nilgoyette** [onur/cargo-license#58]
The new v0.5.0 release broke a feature that was working in v0.4.2.

We have a "virtual manifest" workspace (I'm not sure how to call it, our Cargo.toml is simply linking to other crates). In v0.4.2, we could ask for

    cargo-license -d -t

and it was working. Now it only prints

    No root package

**Comment by dalance** [comment]
Thank you for your report.
I fixed it, and release v0.5.1.

**Comment by nilgoyette** [comment]
It works as it did before, thank you.
