### ISSUE TITLE
Please maintain this

### ISSUE THREAD

**Issue by svenstaro** [onur/cargo-license#65]
Hey, I realize the maintainers of this project might be busy (aren't we all). However, this crate should be maintained as it fulfills a somewhat important role in the ecosystem. If you don't have time to care for this, could you please pass on the maintenance of this crate to some other maintainers?

Please don't take this the wrong way. :)

**Comment by dalance** [comment]
I'm a co-maintainer of this project.

Thank you for your suggestion.
I've missed some PRs. So I'll check them in the next week.

**Comment by svenstaro** [comment]
Thanks for looking into this!

**Comment by dalance** [comment]
I've published v0.5.2.

**Comment by svenstaro** [comment]
Thanks!
