### ISSUE TITLE
0.5.2 contains a breaking change

### ISSUE THREAD

**Issue by sosthene-nitrokey** [onur/cargo-license#70]
`cargo_metadata` is part of the public API of the crate through the [MetaataCommand](https://docs.rs/cargo-license/latest/cargo_license/fn.get_dependencies_from_cargo_lock.html) argument and therefore this is a breaking change, the release should have been 0.6.0.

It would likely make sense to yank 0.5.2 and re-release as 0.6.0.

**Comment by dalance** [comment]
Thank you for your suggestion.
I'll yank and re-release.

**Comment by sosthene-nitrokey** [comment]
Thanks !

And thanks for reviving the project!
