### ISSUE TITLE
Updates also need to bump the Cargo.lock file

### ISSUE THREAD

**Issue by dvzrv** [onur/cargo-license#72]
Hi! :wave: 

I'm currently looking into packaging this crate for Arch Linux (and I see a lot of use-cases to improve our Rust packaging with this here tooling!).

We usually follow our [Rust packaging guidelines](https://wiki.archlinux.org/title/Rust_package_guidelines) when packaging Rust projects.

For this we use `cargo fetch --locked` to fetch the relevant sources to later build (using `cargo build --frozen`).

With the 0.6.0 there is unfortunately a mismatch between the Cargo.toml (project version set to 0.6.0) and the Cargo.lock (project version set to 0.5.2).
This prevents `cargo fetch --locked` and downstreams have to patch the Cargo.lock file before proceeding.

It would be great to include an updated/matching Cargo.lock in upcoming updates.

Thanks for your work on this crate! :clap:

**Comment by dalance** [comment]
Sorry for my mistake.
I'll fix and release v0.6.1.

**Comment by dvzrv** [comment]
No problem at all. Thanks for fixing it so fast! :bow:
